- id: notify_betterstack_heartbeat_check
  alias: Notify BetterStack Heartbeat Check
  description: Heartbeat GET request to the BetterStack heartbeat endpoint every 5
    minutes
  triggers:
  - trigger: time_pattern
    minutes: /5
  actions:
  - action: rest_command.betterstack_heartbeat
    data: {}
  mode: single
- id: '1733774853058'
  alias: sensor light wrkmr1
  description: ''
  use_blueprint:
    path: Blackshome/sensor-light.yaml
    input:
      motion_trigger:
      - binary_sensor.wrkmr1_sen_huemulti_copernicus_occupancy
      light_switch:
        entity_id: light.z2m_wrkmr1_lux_group
      time_delay: 15
      include_ambient: ambient_enabled
      ambient_light_sensor: sensor.wrkmr1_sen_huemulti_copernicus_illuminance
      ambient_light_options: ambient_light_option_enabled
- id: notify_slack_on_ha_restart
  alias: Notify Slack on HA Restart
  description: Send a debug message to Slack when HA restarts
  triggers:
  - trigger: homeassistant
    event: start
  action:
  - action: rest_command.notify_slack
    data:
      channel: '#haos_debug'
      message: ':ha_haos: Home Assistant (192.168.1.26) has restarted at `{{ now().strftime(''%Y-%m-%d
        %H:%M:%S'') }}`

        '
- id: '1733777620780'
  alias: sensor light toilet
  description: ''
  use_blueprint:
    path: Blackshome/sensor-light.yaml
    input:
      motion_trigger:
      - binary_sensor.toilet_sen_huemulti_turing_occupancy
      light_switch:
        entity_id: light.z2m_toilet_lux_group
- id: '1734010555546'
  alias: sensor light badkmr
  description: ''
  use_blueprint:
    path: Blackshome/sensor-light.yaml
    input:
      motion_trigger:
      - binary_sensor.badkmr_sen_huemulti_franklin_occupancy
      light_switch:
        entity_id: light.z2m_badkmr_lux_group
      time_delay: 10
      include_night_lights: night_lights_enabled
      night_lights_conditions:
      - entity_state_enabled
      night_lights_entity_state:
      - input_boolean.r25_var_night_lights_delay
      night_lights:
        entity_id: light.badkmr_lights
      night_time_delay: 1
- id: '1734011013113'
  alias: sensor light bijkkn
  description: ''
  use_blueprint:
    path: Blackshome/sensor-light.yaml
    input:
      motion_trigger:
      - binary_sensor.bijkkn_sen_huemulti_babbage_occupancy
      light_switch:
        entity_id:
        - light.z2m_bijkkn_lux_group
- id: '1734011281640'
  alias: sensor light zitkmr
  description: ''
  use_blueprint:
    path: Blackshome/sensor-light.yaml
    input:
      motion_trigger:
      - binary_sensor.zitkmr_sen_huemulti_celcius_occupancy
      light_switch:
        entity_id: light.z2m_zitkmr_lux_group
      time_delay: 15
      ambient_light_sensor: sensor.zitkmr_sen_huemulti_celcius_illuminance
      ambient_light_options: ambient_light_option_enabled
      ambient_light_value: 220
      ambient_light_high_value: 270
- id: '1734012402875'
  alias: sensor light keuken
  description: ''
  use_blueprint:
    path: Blackshome/sensor-light.yaml
    input:
      motion_trigger:
      - binary_sensor.keuken_sen_huemulti_halley_occupancy
      light_switch:
        entity_id: light.z2m_keuken_lux_group
- id: '1734099648779'
  alias: sensor light pantry
  description: ''
  use_blueprint:
    path: Blackshome/sensor-light.yaml
    input:
      motion_trigger:
      - binary_sensor.pantry_occupancy
      light_switch:
        entity_id: light.z2m_pantry_lux_group
      time_delay: 5
- id: '1741098879096'
  alias: sensor lights overlp
  description: ''
  use_blueprint:
    path: Blackshome/sensor-light.yaml
    input:
      motion_trigger:
      - binary_sensor.overlp_sen_huemulti_alferov_occupancy
      light_switch:
        entity_id: light.z2m_overlp_lux_group
- id: '1741101160785'
  alias: button light slpkmr
  description: ''
  use_blueprint:
    path: patpac9/Hue_Dimmer_Switch_Easy_Custom_Buttons.yaml
    input:
      controller: slpkmr_switch_hueswitch_backus
      on_released:
      - action: light.turn_on
        metadata: {}
        data: {}
        target:
          entity_id: light.z2m_slpkmr_lux_group
      off_released:
      - action: light.turn_off
        metadata: {}
        data: {}
        target:
          entity_id: light.z2m_slpkmr_lux_group
- id: '1741103286010'
  alias: sensor light studio
  description: ''
  use_blueprint:
    path: Blackshome/sensor-light.yaml
    input:
      motion_trigger:
      - binary_sensor.studio_sen_huemulti_cousteau_occupancy
      light_switch:
        entity_id: light.z2m_studio_lux_group
      time_delay: 5
