- id: notify_betterstack_heartbeat_check
  alias: Notify BetterStack Heartbeat Check
  description: Heartbeat GET request to the BetterStack heartbeat endpoint every 5
    minutes
  triggers:
  - trigger: time_pattern
    minutes: /5
  actions:
  - action: rest_command.betterstack_heartbeat
    data: {}
  mode: single
- id: notify_slack_on_ha_restart
  alias: Notify Slack on HA Restart
  description: Send a debug message to Slack when HA restarts
  triggers:
  - trigger: homeassistant
    event: start
  action:
  - action: rest_command.notify_slack
    data:
      channel: '#haos_debug'
      message: ':ha_haos: Home Assistant (192.168.1.26) has restarted at `{{ now().strftime(''%Y-%m-%d
        %H:%M:%S'') }}`

        '
- id: '1733774853058'
  alias: sensor light wrkmr1
  description: ''
  use_blueprint:
    path: Blackshome/sensor-light.yaml
    input:
      motion_trigger:
      - binary_sensor.wrkmr1_sen_huemulti_copernicus_occupancy
      light_switch:
        entity_id: light.z2m_wrkmr1_lux_group
      time_delay: 5
      include_ambient: ambient_enabled
      ambient_light_sensor: sensor.wrkmr1_sen_huemulti_copernicus_illuminance
      ambient_light_options: ambient_light_option_enabled
- id: '1733777620780'
  alias: sensor light toilet
  description: ''
  use_blueprint:
    path: Blackshome/sensor-light.yaml
    input:
      motion_trigger:
      - binary_sensor.toilet_sen_huemulti_turing_occupancy
      light_switch:
        entity_id: light.z2m_toilet_lux_group
      time_delay: 2
- id: '1734010555546'
  alias: sensor light badkmr
  description: ''
  use_blueprint:
    path: Blackshome/sensor-light.yaml
    input:
      motion_trigger:
      - binary_sensor.badkmr_sen_huemulti_franklin_occupancy
      light_switch:
        entity_id: light.z2m_badkmr_lux_group
      time_delay: 8
      include_night_lights: night_lights_enabled
      night_lights_conditions:
      - entity_state_enabled
      night_lights_entity_state:
      - input_boolean.r25_var_night_lights_delay
      night_lights:
        entity_id: light.badkmr_lights
      night_time_delay: 1
- id: '1734011013113'
  alias: sensor light bijkkn
  description: ''
  use_blueprint:
    path: Blackshome/sensor-light.yaml
    input:
      motion_trigger:
      - binary_sensor.bijkkn_sen_huemulti_babbage_occupancy
      light_switch:
        entity_id:
        - light.z2m_bijkkn_lux_group
      time_delay: 2
- id: '1734011281640'
  alias: sensor light zitkmr
  description: ''
  use_blueprint:
    path: Blackshome/sensor-light.yaml
    input:
      motion_trigger:
      - binary_sensor.zitkmr_sen_huemulti_celcius_occupancy
      light_switch:
        entity_id: light.z2m_zitkmr_lux_group
      time_delay: 15
      ambient_light_sensor: sensor.zitkmr_sen_huemulti_celcius_illuminance
      ambient_light_options: ambient_light_option_enabled
      ambient_light_value: 200
      ambient_light_high_value: 220
      include_ambient: ambient_enabled
- id: '1734012402875'
  alias: sensor light keuken
  description: ''
  use_blueprint:
    path: Blackshome/sensor-light.yaml
    input:
      motion_trigger:
      - binary_sensor.keuken_occupancy
      light_switch:
        entity_id: light.z2m_keuken_lux_group
      time_delay: 5
      include_ambient: ambient_enabled
      ambient_light_sensor: sensor.keuken_sen_huemulti_halley_illuminance
      ambient_light_value: 100
      ambient_light_high_value: 150
      ambient_light_options: ambient_light_option_enabled
- id: '1734099648779'
  alias: sensor light pantry
  description: ''
  use_blueprint:
    path: Blackshome/sensor-light.yaml
    input:
      motion_trigger:
      - binary_sensor.pantry_occupancy
      light_switch:
        entity_id: light.z2m_pantry_lux_group
      time_delay: 1
- id: '1741098879096'
  alias: sensor light overlp
  description: ''
  use_blueprint:
    path: Blackshome/sensor-light.yaml
    input:
      motion_trigger:
      - binary_sensor.overlp_sen_huemulti_alferov_occupancy
      light_switch:
        entity_id: light.z2m_overlp_lux_group
      time_delay: 2
      include_ambient: ambient_enabled
      ambient_light_sensor: sensor.overlp_sen_huemulti_alferov_illuminance
      ambient_light_value: 250
      ambient_light_high_value: 500
      ambient_light_options: ambient_light_option_enabled
- id: '1741101160785'
  alias: button light slpkmr
  description: ''
  use_blueprint:
    path: patpac9/Hue_Dimmer_Switch_Easy_Custom_Buttons.yaml
    input:
      controller: slpkmr_switch_hueswitch_backus
      on_released:
      - action: light.turn_on
        metadata: {}
        data: {}
        target:
          entity_id: light.z2m_slpkmr_lux_group
      off_released:
      - action: light.turn_off
        metadata: {}
        data: {}
        target:
          entity_id: light.z2m_slpkmr_lux_group
- id: '1741101160786'
  alias: button light wrkmr2
  description: ''
  use_blueprint:
    path: patpac9/Hue_Dimmer_Switch_Easy_Custom_Buttons.yaml
    input:
      controller: wrkmr2_switch_hueswitch_gelding
      on_released:
      - action: light.turn_on
        metadata: {}
        data: {}
        target:
          entity_id: light.z2m_wrkmr2_lux_group
      off_released:
      - action: light.turn_off
        metadata: {}
        data: {}
        target:
          entity_id: light.z2m_wrkmr2_lux_group
      down_released:
      - service: light.turn_on
        metadata: {}
        data:
          brightness_step_pct: -20
          transition: 2
        target:
          entity_id: light.z2m_wrkmr2_lux_group
      up_released:
      - service: light.turn_on
        metadata: {}
        data:
          brightness_step_pct: 20
          transition: 2
        target:
          entity_id: light.z2m_wrkmr2_lux_group
- id: '1741103286010'
  alias: sensor light studio
  description: ''
  use_blueprint:
    path: Blackshome/sensor-light.yaml
    input:
      motion_trigger:
      - binary_sensor.studio_sen_huemulti_cousteau_occupancy
      light_switch:
        entity_id: light.z2m_studio_lux_group
      time_delay: 5
- id: '1745585694435'
  alias: sensor light entree
  description: ''
  use_blueprint:
    path: Blackshome/sensor-light.yaml
    input:
      motion_trigger:
      - binary_sensor.entree_occupancy
      light_switch:
        entity_id: light.z2m_entree_lux_group
      time_delay: 2
      include_ambient: ambient_enabled
      ambient_light_sensor: sensor.entree_illuminance
      ambient_light_options: ambient_light_option_enabled
      ambient_light_value: 70
      ambient_light_high_value: 150
- id: '1747688006282'
  alias: sensor light achttn
  description: ''
  use_blueprint:
    path: Blackshome/sensor-light.yaml
    input:
      motion_trigger:
      - binary_sensor.achttn_occupancy
      light_switch:
        entity_id: light.achttn_lux_hueflood_davy
      time_delay: 1
      include_ambient: ambient_enabled
      ambient_light_sensor: sensor.achttn_sen_huemultioutdoor_weber_illuminance
      ambient_light_options: ambient_light_option_enabled
      ambient_light_value: 10
      ambient_light_high_value: 30
- id: '1747863852547'
  alias: sensor light sauna
  description: ''
  use_blueprint:
    path: Blackshome/sensor-light.yaml
    input:
      motion_trigger:
      - binary_sensor.sauna_occupancy
      include_ambient: ambient_enabled
      ambient_light_sensor: sensor.achttn_sen_huemultioutdoor_weber_illuminance
      ambient_light_options: ambient_light_option_enabled
      ambient_light_value: 10
      ambient_light_high_value: 50
      light_switch:
        entity_id:
        - light.z2m_sauna_virtual_lux_group
      time_delay: 15
- id: '1748288187441'
  alias: sensor light kelder
  description: ''
  use_blueprint:
    path: Blackshome/sensor-light.yaml
    input:
      motion_trigger:
      - binary_sensor.kelder_occupancy
      light_switch:
        entity_id: light.z2m_kelder_lux_group
- id: '1750258673697'
  alias: sensor light kelder override
  description: ''
  triggers:
  - trigger: state
    entity_id:
    - binary_sensor.kelder_occupancy
    from: 'on'
    to: 'off'
  conditions:
  - condition: state
    entity_id: binary_sensor.kelder_sen_3rdtilt_tiltstra_contact
    state: 'on'
  actions:
  - type: turn_off
    device_id: a5153a57e87585a2906ffccf2bfef739
    entity_id: 7a8f6b7afc7a3bd61b749ab891f67255
    domain: light
  mode: single
- id: '1751145004347'
  alias: Button Light Wingquist On
  triggers:
  - entity_id: event.wingquist_action
    to:
    trigger: state
  conditions:
  - condition: template
    value_template: '{{ state_attr(''event.wingquist_action'', ''event_type'') ==
      ''on'' }}'
  actions:
  - target:
      entity_id: light.z2m_wrkmr1_lux_group
    action: light.turn_on
  mode: single
- id: '1751145041342'
  alias: Button Light Wingquist Off
  triggers:
  - entity_id: event.wingquist_action
    to:
    trigger: state
  conditions:
  - condition: template
    value_template: '{{ state_attr(''event.wingquist_action'', ''event_type'') ==
      ''off'' }}'
  actions:
  - target:
      entity_id: light.z2m_wrkmr1_lux_group
    action: light.turn_off
  mode: single
