version: 4
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://core-mosquitto:1883
  user: addons
  password: thai1abeiM8Apahth5eereez5dooquaa5oojoangeedei9Einiesh1Faijeija6j
serial:
  adapter: zstack
  baudrate: 115200
  rtscts: false
  port: /dev/ttyUSB0
advanced:
  log_level: info
  channel: 11
  network_key:
    - 110
    - 175
    - 32
    - 237
    - 21
    - 137
    - 153
    - 11
    - 131
    - 207
    - 87
    - 95
    - 123
    - 39
    - 37
    - 30
  pan_id: 32162
  ext_pan_id:
    - 117
    - 174
    - 104
    - 50
    - 236
    - 232
    - 130
    - 20
frontend:
  enabled: true
  package: zigbee2mqtt-windfront
  port: 8099
homeassistant:
  enabled: true
availability:
  enabled: true
devices:
  '0x0017880102dee36a':
    friendly_name: zitkmr_lux_huebulb_gauss
  '0x0017880102b06a0b':
    friendly_name: zitkmr_lux_huebulb_huygens
  '0x54ef4410000fed29':
    friendly_name: zitkmr_pow_aqasock_galvani
  '0x385b44fffe1d770e':
    friendly_name: zitkmr_pow_ikesock_braun
  '0x001788010bf87e4f':
    friendly_name: zitkmr_lux_huebulb_montagu
  '0x001788010bf8c3b8':
    friendly_name: zitkmr_lux_huebulb_mccormack
  '0x001788010b9dad70':
    friendly_name: zitkmr_lux_hueorb_swainson
  '0x403059fffee6f7b7':
    friendly_name: keuken_lux_ikestoft_townes
  '0x943469fffe642e9b':
    friendly_name: pantry_lux_ikestoft_schiff
  '0x385cfbfffe6ca692':
    friendly_name: pantry_lux_ikestoft_einstein
  '0xd44867fffe8977b9':
    friendly_name: keuken_lux_ikestoft_schawlow
  '0x403059fffe4cf7c7':
    friendly_name: bijkkn_lux_ikestoft_basov
  '0x001788010e7eda21':
    friendly_name: entree_lux_huebeing_coolidge
  '0x30fb10fffe22e10a':
    friendly_name: overlp_lux_ikestoft_hall
  '0x0017880106400af9':
    friendly_name: slpkmr_lux_hueplay_doppler
  '0x385b44fffe1a2d1b':
    friendly_name: slpkmr_pow_ikesock_ockham
  '0x001788010b3f49bd':
    friendly_name: slpkmr_lux_huebloom_drexler
  '0x943469fffe6457b6':
    friendly_name: badkmr_lux_ikestoft_gould
  '0x403059fffe4cb403':
    friendly_name: wrkmr2_lux_ikestoft_prokhorov
  '0x403059fffe4cdfb1':
    friendly_name: wrkmr1_lux_ikestoft_javan
  '0xbc33acfffe0e1b71':
    friendly_name: wrkmr1_lux_ikespot_kelvin
  '0xbc33acfffe13994a':
    friendly_name: wrkmr1_lux_ikespot_newton
  '0xbc33acfffe0ce18c':
    friendly_name: wrkmr1_lux_ikespot_celcius
  '0x001788010eec4290':
    friendly_name: slpkmr_lux_huespot_nakamura
  '0x001788010ee4511d':
    friendly_name: slpkmr_lux_huespot_amano
  '0x0017880109ea9306':
    friendly_name: slpkmr_lux_hueplay_bunsen
  '0x001788010ee45994':
    friendly_name: slpkmr_lux_huespot_akasaki
  '0x001788010bb53f81':
    friendly_name: toilet_lux_huespot_thompson
  '0x001788010bb53f7b':
    friendly_name: toilet_lux_huespot_templeton
  '0x44e2f8fffef88a66':
    friendly_name: kelder_lux_ikepanel_langmuir
  '0x44e2f8fffe4bbfe6':
    friendly_name: kelder_lux_ikepanel_holonyak
  '0x44e2f8fffe4bbf54':
    friendly_name: kelder_lux_ikepanel_biard
  '0x0017880104c8de92':
    friendly_name: studio_lux_huebulb_marcelin
  '0x001788010423d9e0':
    friendly_name: studio_lux_huebulb_reaumur
  '0x0017880104102670':
    friendly_name: studio_lux_huebulb_laennec
  '0x04cf8cdf3c89e786':
    friendly_name: studio_pow_aqasock_watt
  '0x04cf8cdf3c7c21ad':
    friendly_name: kelder_pow_aqasock_leeuwenhoek
  '0x000b3cfffef2a81c':
    friendly_name: kelder_pow_ikesock_whitney
  '0x00158d00024030ae':
    friendly_name: kelder_sen_aqaleak_watson
  '0xffffb40e0601a0f7':
    friendly_name: kelder_sen_3rdtilt_tiltstra
  '0x001788010cd66406':
    friendly_name: kelder_sen_huemulti_vanrossum
  '0x001788010cd9f99a':
    friendly_name: kelder_sen_huemulti_lamarr
  '0x00158d0003498551':
    friendly_name: kelder_sen_aqatemp_stihl
  '0x00158d00036bd4e2':
    friendly_name: kelder_sen_aqatemp_lans
  '0xa4c1389a89b856ec':
    friendly_name: kelder_bot_tuybot_bird
  '0x7c3e820001260000':
    friendly_name: kelder_sen_3rdtemp_ximena
  '0x0017880102031631':
    friendly_name: studio_sen_huemulti_cousteau
  '0x7c3e820005280000':
    friendly_name: kelder_sen_3rdtemp_yanet
  '0x282c02bfffefc381':
    friendly_name: kelder_sen_3rdleak_goode
  '0x282c02bfffefbcb4':
    friendly_name: kelder_sen_3rdleak_clarke
  '0x0017880106f54afa':
    friendly_name: pantry_sen_huemulti_bernerslee
  '0x0017880106f7f3d8':
    friendly_name: pantry_sen_huemulti_curie
  '0x0017880106f57744':
    friendly_name: keuken_sen_huemulti_halley
  '0x00158d008b040482':
    friendly_name: eetkmr_sen_aqatemp_sommer
  '0x001788010cd668a0':
    friendly_name: eetkmr_sen_huemulti_woodhouse
  '0x00178801032a1b90':
    friendly_name: zitkmr_sen_huemulti_celcius
  '0x001788010df93f15':
    friendly_name: entree_sen_huemulti_bardeen
  '0x001788010df9376b':
    friendly_name: entree_sen_huemulti_abbott
  '0x001788010329fc00':
    friendly_name: bijkkn_sen_huemulti_babbage
  '0x001788010862ffd2':
    friendly_name: toilet_sen_huemulti_turing
  '0x001788010df9588c':
    friendly_name: overlp_sen_huemulti_alferov
  '0x0017880104ac1670':
    friendly_name: slpkmr_switch_hueswitch_backus
  '0x0017880106f7fda9':
    friendly_name: badkmr_sen_huemulti_franklin
  '0x00178801032a158f':
    friendly_name: wrkmr1_sen_huemulti_copernicus
  '0x001788010e8a1647':
    friendly_name: wrkmr2_switch_hueswitch_gelding
  '0x00178801064022fb':
    friendly_name: slpkmr_lux_hueplay_kepler
  '0x0017880104cdc863':
    friendly_name: keuken_lux_huespot_dubos
  '0x0017880104c36f02':
    friendly_name: keuken-lux-huespot-blondlot
  '0x0017880104cdc85f':
    friendly_name: keuken-lux-huespot-bernasconi
  '0x0017880106fc8a23':
    friendly_name: achttn_lux_hueflood_davy
  '0xf0d1b8be24086922':
    friendly_name: sauna_pow_ledsock_stroustrup
  '0xf0d1b8be2408693d':
    friendly_name: patio_pow_ledsock_karlstrup
  '0x001788010df771e5':
    friendly_name: achttn_sen_huemultioutdoor_townes
  '0x001788010df7720c':
    friendly_name: achttn_sen_huemultioutdoor_weber
  '0x0017880106473c83':
    friendly_name: achttn_sen_huemultioutdoor_herschel
  '0x00178801064489db':
    friendly_name: voortn_sen_huemultioutdoor_bell
  '0x7c3e8200f7b30000':
    friendly_name: kelder_sen_3rdtemp_tempstra
  '0x00158d0006692356':
    friendly_name: pantry_sen_aqatemp_westra
  '0xf0d1b8be240874a8':
    friendly_name: landing_pow_ledsock_laudrup
  '0xffffb40e06019e6d':
    friendly_name: voortn_sen_3rdvibr_richter
  '0xe0798dfffed1b802':
    friendly_name: sonoff_zbdongle-e_router
  '0x00158d000af3945f':
    friendly_name: achttn_sen_aqatemp_maxim
  '0xffffb40e06059575':
    friendly_name: achttn_sen_3rdmoist_beachell
  '0xffffb40e060596cd':
    friendly_name: achttn_sen_3rdmoist_martin
  '0xffffb40e0600b3ea':
    friendly_name: achttn_sen_3rdmoist_borlaug
  '0xf0d1b8be24086cfb':
    friendly_name: quay_pow_ledsock_ekstrup
  '0x04cf8cdf3c89f257':
    friendly_name: studio_pow_aqasock_tesla
  '0x54ef4410000ff1b9':
    friendly_name: studio_pow_aqasock_joule
  '0x04cf8cdf3c8d047f':
    friendly_name: studio_pow_aqasock_ohm
  '0x54ef4410004a686c':
    friendly_name: achttn_cov_aqacurt_rosenberg
  '0x00158d0007e02a84':
    friendly_name: voortn_sen_aqadoor_carson
groups:
  '1':
    friendly_name: z2m_zitkmrhue_lux_group
  '2':
    friendly_name: z2m_zitkmr_lux_group
  '3':
    friendly_name: z2m_keuken_lux_group
  '4':
    friendly_name: z2m_wrkmr1_lux_group
  '5':
    friendly_name: z2m_toilet_lux_group
  '6':
    friendly_name: z2m_wrkmr2_lux_group
  '7':
    friendly_name: z2m_overlp_lux_group
  '8':
    friendly_name: z2m_slpkmr_lux_group
  '9':
    friendly_name: z2m_buiten_pow_group
  '10':
    friendly_name: z2m_kelder_lux_group
  '11':
    friendly_name: z2m_studio_lux_group
  '12':
    friendly_name: z2m_bijkkn_lux_group
  '13':
    friendly_name: z2m_entree_lux_group
  '14':
    friendly_name: z2m_eetkmr_lux_group
  '15':
    friendly_name: z2m_badkmr_lux_group
  '16':
    friendly_name: z2m_pantry_lux_group
  '17':
    friendly_name: z2m_achttn_lux_group
