homeassistant: true
advanced:
  network_key:
    - 188
    - 247
    - 230
    - 180
    - 88
    - 118
    - 226
    - 54
    - 5
    - 185
    - 173
    - 78
    - 129
    - 214
    - 144
    - 72
  pan_id: 49438
  ext_pan_id:
    - 44
    - 73
    - 211
    - 135
    - 98
    - 1
    - 12
    - 238
mqtt:
  server: mqtt://core-mosquitto:1883
  user: addons
  password: thai1abeiM8Apahth5eereez5dooquaa5oojoangeedei9Einiesh1Faijeija6j
serial:
  port: /dev/ttyACM0
  adapter: deconz
frontend:
  port: 8099
devices: {}
