homeassistant: true
advanced:
  network_key:
    - 67
    - 148
    - 79
    - 71
    - 81
    - 232
    - 214
    - 124
    - 137
    - 136
    - 198
    - 47
    - 56
    - 234
    - 32
    - 219
  pan_id: 19685
  ext_pan_id:
    - 105
    - 10
    - 216
    - 75
    - 236
    - 151
    - 141
    - 251
mqtt:
  server: mqtt://core-mosquitto:1883
  user: addons
  password: thai1abeiM8Apahth5eereez5dooquaa5oojoangeedei9Einiesh1Faijeija6j
serial:
  port: /dev/ttyACM0
frontend:
  port: 8099
