homeassistant:
  enabled: true
  experimental_event_entities: true
  legacy_action_sensor: true
mqtt:
  server: mqtt://core-mosquitto:1883
  user: addons
  password: thai1abeiM8Apahth5eereez5dooquaa5oojoangeedei9Einiesh1Faijeija6j
serial:
  port: /dev/ttyACM0
  adapter: deconz
frontend:
  enabled: true
  port: 8099
ota:
  ikea_ota_use_test_url: false
advanced:
  log_level: info
  homeassistant_legacy_entity_attributes: false
  homeassistant_legacy_triggers: false
  legacy_api: false
  legacy_availability_payload: false
device_options:
  legacy: false
availability:
  enabled: true
devices:
  '0xe0798dfffed1b802':
    friendly_name: sonoff_zbdongle-e_router
  '0x00178801064489db':
    friendly_name: voortn_sen_huemultioutdoor_bell
  '0x003c84fffe6a9791':
    friendly_name: zitkmr_lux_livfloor_gilbert2
  '0x00158d008b040482':
    friendly_name: eetkmr_sen_aqatemp_sommer
  '0x54ef4410000fed29':
    friendly_name: galvani
  '0x84ba20fffe830e15':
    friendly_name: zitkmr_lux_livfloor_gilbert1
  '0x0017880102dee36a':
    friendly_name: zitkmr_lux_huebulb_gauss
  '0x0017880102b06a0b':
    friendly_name: zitkmr_lux_huebulb_huygens
  '0x0017880106f7f3d8':
    friendly_name: closet_sen_huemulti_curie
  '0x0017880106f57744':
    friendly_name: keuken_sen_huemulti_halley
  '0x00178801032a1b90':
    friendly_name: zitkmr_sen_huemulti_celcius
  '0x0017880104c8de92':
    friendly_name: studio_lux_huebulb_marcelin
  '0x001788010423d9e0':
    friendly_name: studio_lux_huebulb_reaumur
  '0x5c0272fffe627239':
    friendly_name: _pow_ikesock_geiger_heater
  '0x385b44fffe1a2d1b':
    friendly_name: slpkmr_pow_ikesock_ockham_heater
  '0x086bd7fffe0042f0':
    friendly_name: studio_pow_ikesock_talbot
  '0x385b44fffe1d770e':
    friendly_name: zitkmr_pow_ikesock_braun
  '0x000d6ffffeaa2be9':
    friendly_name: wrkmr1_pow_ikesock_volta_heater
  '0x54ef4410004a686c':
    friendly_name: huberman
  '0xf0d1b8be24086922':
    friendly_name: buiten_pow_ledsock_stroustrup
  '0x000d6ffffedecccd':
    friendly_name: kelder_pow_ikesock_farad
  '0x000b3cfffef2a81c':
    friendly_name: kelder_pow_ikesock_whitney
  '0x00178801032a158f':
    friendly_name: wrkmr1_sen_huemulti_copernicus
  '0x0017880102dee9ab':
    friendly_name: bijkkn_lux_huebulb_gatso
  '0x001788010b9dad70':
    friendly_name: zitkmr_lux_hueorb_swainson
  '0x0017880104cdc863':
    friendly_name: keuken_lux_huespot_dubos
  '0x0017880104c36f02':
    friendly_name: keuken-lux-huespot-blondlot
  '0x0017880104cdc85f':
    friendly_name: keuken-lux-huespot-bernasconi
  '0x0017880106400af9':
    friendly_name: slpkmr_lux_hueplay_doppler
  '0x0017880109ea9306':
    friendly_name: slpkmr_lux_hueplay_bunsen
  '0x00178801064022fb':
    friendly_name: slpkmr_lux_hueplay_kepler
  '0x001788010b3f49bd':
    friendly_name: slpkmr_lux_huebloom_drexler
  '0x001788010cd9f99a':
    friendly_name: _wrkmr2_sen_huemulti_lamarr
  '0x04cd15fffe81741e':
    friendly_name: '0x04cd15fffe81741e'
  '0x0017880106f7fda9':
    friendly_name: badkmr_sen_huemulti_franklin
  '0xdc8e95fffe8e9283':
    friendly_name: '0xdc8e95fffe8e9283'
  '0x001788010329fc00':
    friendly_name: bijkkn_sen_huemulti_babbage
  '0x0c4314fffeec88cd':
    friendly_name: '0x0c4314fffeec88cd'
  '0x001788010e6adabb':
    friendly_name: overlp_lux_huebulb_knuth
  '0x001788010e1f19ac':
    friendly_name: keuken_lux_huebulb_ritchie
  '0x001788010e6ac3b3':
    friendly_name: keuken_lux_huebulb_wiener
  '0x001788010df9588c':
    friendly_name: overlp_sen_huemulti_alferov
  '0x001788010862ffd2':
    friendly_name: toilet_sen_huemulti_turing
  '0x001788010cd66406':
    friendly_name: _sen_huemulti_abbott
  '0x0017880102031631':
    friendly_name: studio_sen_huemulti_cousteau
  '0x0017880106f54afa':
    friendly_name: pantry_sen_huemulti_bernerslee
  '0x001788010df9376b':
    friendly_name: _sen_huemulti_vanrossum
  '0x0017880104ac1670':
    friendly_name: slpkmr_switch_hueswitch_backus
  '0xbc33acfffe0e1b71':
    friendly_name: wrkmr1_lux_ikespot_kelvin
  '0xbc33acfffe0ce18c':
    friendly_name: wrkmr1_lux_ikespot_celcius
  '0xbc33acfffe13994a':
    friendly_name: wrkmr1_lux_ikespot_newton
  '0x943469fffe6457b6':
    friendly_name: badkmr_lux_ikestoft_gould
  '0x00158d0002ec0e29':
    friendly_name: _sen_aqadoor_popov
  '0x001788010df93f15':
    friendly_name: _sen_huemulti_bardeen
  '0x001788010cd668a0':
    friendly_name: eetkmr_sen_huemulti_woodhouse
  '0x04cd15fffea027fd':
    friendly_name: studio_lux_livdesk_gilbert3
  '0x04cd15fffe789900':
    friendly_name: studio_lux_livdesk_gilbert4
  '0x000d6ffffe08bb20':
    friendly_name: '0x000d6ffffe08bb20'
  '0xf0d1b8be2408693d':
    friendly_name: buiten_pow_ledsock_karlstrup
  '0xf0d1b8be240874a8':
    friendly_name: buiten_pow_ledsock_laudrup
  '0x00158d0007e02a84':
    friendly_name: kelder_sen_aqadoor_sutton
  '0xf0d1b8be24086cfb':
    friendly_name: buiten_pow_ledsock_skovstrup
  '0x001788010bb53f7b':
    friendly_name: toilet_lux_huespot_templeton
  '0x001788010bb534ab':
    friendly_name: toilet_lux_huespot_thompson
  '0x54ef44100060c226':
    friendly_name: '0x54ef44100060c226'
  '0x2c1165fffe3008c8':
    friendly_name: pantry_lux_ikebulb_maybach
  '0x001788010412a882':
    friendly_name: closet_lux_ikebulb_planck
  '0x54ef44100060ac97':
    friendly_name: '0x54ef44100060ac97'
  '0x04cf8cdf3c8d047f':
    friendly_name: eetkmr_pow_aqasock_ohm_heater
  '0x54ef4410000ff1b9':
    friendly_name: zitkmr_pow_aqasock_joule_heater
  '0x04cf8cdf3c89f257':
    friendly_name: zitkmr_pow_aqasock_tesla_heater
  '0x0017880104102670':
    friendly_name: studio_lux_huebulb_laennec
  '0x04cf8cdf3c89e786':
    friendly_name: wrkmr1_pow_aqasock_watt_heater
blocklist: []
groups:
  '1':
    friendly_name: z2m_zitkmrhue_lux_group
  '2':
    friendly_name: z2m_zitkmr_lux_group
  '3':
    friendly_name: z2m_keuken_lux_group
  '4':
    friendly_name: z2m_wrkmr1_lux_group
  '5':
    friendly_name: z2m_toilet_lux_group
  '6':
    friendly_name: z2m_wrkmr2_lux_group
  '7':
    friendly_name: z2m_overlp_lux_group
  '8':
    friendly_name: z2m_slpkmr_lux_group
  '9':
    friendly_name: z2m_buiten_pow_group
  '10':
    friendly_name: z2m_kelder_lux_group
  '11':
    friendly_name: z2m_studio_lux_group
  '12':
    friendly_name: z2m_bijkkn_lux_group
  '13':
    friendly_name: z2m_entree_lux_group
  '14':
    friendly_name: z2m_eetkmr_lux_group
  '15':
    friendly_name: z2m_badkmr_lux_group
  '16':
    friendly_name: z2m_zitkmrliv_lux_group
  '17':
    friendly_name: z2m_pantry_lux_group
version: 4
