homeassistant:
  enabled: true
  experimental_event_entities: true
  legacy_action_sensor: true
mqtt:
  server: mqtt://core-mosquitto:1883
  user: addons
  password: thai1abeiM8Apahth5eereez5dooquaa5oojoangeedei9Einiesh1Faijeija6j
serial:
  port: /dev/ttyACM0
  adapter: deconz
frontend:
  enabled: true
  port: 8099
ota:
  ikea_ota_use_test_url: false
advanced:
  log_level: info
  homeassistant_legacy_entity_attributes: false
  homeassistant_legacy_triggers: false
  legacy_api: false
  legacy_availability_payload: false
device_options:
  legacy: false
availability:
  enabled: true
devices:
  '0xe0798dfffed1b802':
    friendly_name: sonoff_zbdongle-e_router
  '0x00178801064489db':
    friendly_name: voortn_sen_huemultioutdoor_bell
  '0x003c84fffe6a9791':
    friendly_name: zitkmr_lux_livfloor_gilbert2
  '0x00158d008b040482':
    friendly_name: eetkmr_sen_aqatemp_sommer
  '0x54ef4410000fed29':
    friendly_name: galvani
  '0x84ba20fffe830e15':
    friendly_name: zitkmr_lux_livfloor_gilbert1
  '0x0017880102dee36a':
    friendly_name: zitkmr_lux_huebulb_gauss
  '0x0017880102b06a0b':
    friendly_name: zitkmr_lux_huebulb_huygens
  '0x0017880106f7f3d8':
    friendly_name: _eetkmr_sen_huemulti_curie
  '0x0017880106f57744':
    friendly_name: keuken_sen_huemulti_halley
  '0x00178801032a1b90':
    friendly_name: _zitkmr_sen_huemulti_celcius
  '0x0017880104c8de92':
    friendly_name: kelder_lux_huebulb_marcelin
  '0x001788010423d9e0':
    friendly_name: kelder_lux_huebulb_reaumur
  '0x0017880104102670':
    friendly_name: kelder_lux_huebulb_laennec
  '0x0017880100d68537':
    friendly_name: kelder_lux_huebulb_shannon
  '0x5c0272fffe627239':
    friendly_name: wookmr_pow_ikesock_geiger_heater
  '0x385b44fffe1a2d1b':
    friendly_name: wookmr_pow_ikesock_ockham_heater
  '0x086bd7fffe0042f0':
    friendly_name: entree_pow_ikesock_talbot
  '0x385b44fffe1d770e':
    friendly_name: pantry_pow_ikesock_brown
  '0x000d6ffffeaa2be9':
    friendly_name: wrkmr1_pow_ikesock_volta_heater
  '0x54ef4410004a686c':
    friendly_name: huberman
  '0xf0d1b8be24086922':
    friendly_name: buiten_pow_ledsock_stroustrup
  '0x000d6ffffedecccd':
    friendly_name: kelder_pow_ikesock_farad
  '0x000b3cfffef2a81c':
    friendly_name: kelder_pow_ikesock_whitney
  '0x00178801032a158f':
    friendly_name: _wrkmr1_sen_huemulti_copernicus
  '0x0017880102dee9ab':
    friendly_name: bijkkn_lux_huebulb_gatso
  '0x001788010b9dad70':
    friendly_name: overlp_lux_hueorb_swainson
  '0x0017880104cdc863':
    friendly_name: keuken_lux_huespot_dubos
  '0x0017880104c36f02':
    friendly_name: keuken-lux-huespot-blondlot
  '0x0017880104cdc85f':
    friendly_name: keuken-lux-huespot-bernasconi
  '0x0017880106400af9':
    friendly_name: slpkmr_lux_hueplay_doppler
  '0x0017880109ea9306':
    friendly_name: slpkmr_lux_hueplay_bunsen
  '0x00178801064022fb':
    friendly_name: slpkmr_lux_hueplay_kepler
  '0x001788010b3f49bd':
    friendly_name: slpkmr_lux_huebloom_drexler
  '0x001788010cd9f99a':
    friendly_name: _wrkmr2_sen_huemulti_lamarr
  '0x04cd15fffe81741e':
    friendly_name: '0x04cd15fffe81741e'
  '0x0017880106f7fda9':
    friendly_name: badkmr_sen_huemulti_franklin
  '0xdc8e95fffe8e9283':
    friendly_name: '0xdc8e95fffe8e9283'
  '0x001788010329fc00':
    friendly_name: bijkkn_sen_huemulti_babbage
  '0x0c4314fffeec88cd':
    friendly_name: '0x0c4314fffeec88cd'
  '0x001788010e6adabb':
    friendly_name: overlp_lux_huebulb_knuth
  '0x001788010e1f19ac':
    friendly_name: keuken_lux_huebulb_ritchie
  '0x001788010e6ac3b3':
    friendly_name: keuken_lux_huebulb_wiener
  '0x001788010df9588c':
    friendly_name: overlp_sen_huemulti_alferov
  '0x001788010862ffd2':
    friendly_name: _sen_huemulti_turing
  '0x001788010cd66406':
    friendly_name: _sen_huemulti_abbott
  '0x0017880102031631':
    friendly_name: kelder_sen_huemulti_cousteau
  '0x0017880106f54afa':
    friendly_name: _sen_huemulti_bernerslee
  '0x001788010df9376b':
    friendly_name: _sen_huemulti_vanrossum
  '0x0017880104ac1670':
    friendly_name: slpkmr_switch_hueswitch_backus
  '0xbc33acfffe0e1b71':
    friendly_name: wrkmr1_lux_ikespot_kelvin
  '0xbc33acfffe0ce18c':
    friendly_name: wrkmr1_lux_ikespot_celcius
  '0xbc33acfffe13994a':
    friendly_name: wrkmr1_lux_ikespot_newton
  '0x943469fffe6457b6':
    friendly_name: badkmr_lux_ikestoft_gould
  '0x00158d0002ec0e29':
    friendly_name: _sen_aqadoor_popov
  '0x001788010df93f15':
    friendly_name: _sen_huemulti_bardeen
  '0x001788010cd668a0':
    friendly_name: eetkmr_sen_huemulti_woodhouse
blocklist: []
groups:
  '1':
    friendly_name: wrkmr1
version: 4
